name: release

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag and release to create. Must be in format "vX.Y.Z"'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag
        run: |
          if [[ ! ${{ github.events.inputs.tag }} =~ "v[0-9]+\.[0-9]+\.[0-9]+" ]]; then
            echo "Bad value supplied for version tag"
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      - run: go version
      - name: Login to ccp-infra registry
        run: docker login -u ${DO_API_TOKEN} -p ${DO_API_TOKEN} registry.digitalocean.com
        env:
          DO_API_TOKEN: ${{ secrets.APIToken }}
      - name: Publish Docker Image
        env:
          VERSION: ${{ github.event.inputs.tag }}
        run: make publish